services:
  backend:
    image: nireekshahuns/task-tracker-backend:prod
    container_name: task-tracker-backend-prod
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env.prod
    volumes:
      - task-data-prod:/app/data

  frontend:
    image: nireekshahuns/task-tracker-frontend:latest
    container_name: task-tracker-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env.dev
    depends_on:
      - backend

volumes:
  task-data-prod:
    driver: local
